[0m19:10:27.058384 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb9d9beec40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb9d8f9e2b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb9d8f9ebb0>]}


============================== 19:10:27.063291 | c9d8b813-6efb-4187-a5aa-0423607acca0 ==============================
[0m19:10:27.063291 [info ] [MainThread]: Running with dbt=1.9.1
[0m19:10:27.063813 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/juusovayrynen/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m19:10:27.071037 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object.. Dictionary: {'dir': PosixPath('/Users/juusovayrynen/.dbt')}
[0m19:10:27.071351 [info ] [MainThread]: Creating dbt configuration folder at 
[0m19:10:39.105004 [debug] [MainThread]: Starter project path: /opt/anaconda3/lib/python3.9/site-packages/dbt/include/starter_project
[0m19:10:39.117306 [info ] [MainThread]: 
Your new dbt project "custom_postgres" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m19:10:39.118123 [info ] [MainThread]: Setting up your profile.
[0m19:15:05.219067 [info ] [MainThread]: Profile custom_postgres written to /Users/juusovayrynen/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m19:15:05.377178 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 278.65332, "process_in_blocks": "0", "process_kernel_time": 0.145548, "process_mem_max_rss": "91545600", "process_out_blocks": "0", "process_user_time": 0.802859}
[0m19:15:05.378061 [debug] [MainThread]: Command `dbt init` succeeded at 19:15:05.377817 after 278.65 seconds
[0m19:15:05.378396 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb9d9beec40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb9b8384af0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb9d8f8e3d0>]}
[0m19:15:05.378711 [debug] [MainThread]: Flushing usage events
[0m19:15:06.016030 [debug] [MainThread]: An error was encountered while trying to flush usage events
